basePath: /api
definitions:
  handlers.AuditRequest:
    properties:
      category:
        description: 카테고리 검증 제거
        type: string
      host:
        type: string
      os:
        description: OS 타입 추가
        enum:
        - ubuntu
        - xenserver
        type: string
      password:
        type: string
      script:
        type: string
      username:
        type: string
    required:
    - category
    - host
    - os
    - password
    - script
    - username
    type: object
  handlers.AuditResult:
    properties:
      details:
        type: string
      result:
        type: string
      timestamp:
        type: string
      title:
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      error:
        example: error message
        type: string
    type: object
  handlers.HealthResponse:
    properties:
      status:
        type: string
      timestamp:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: your-email@example.com
    name: API Support
  description: Security compliance scanning and monitoring system for multiple operating
    systems
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: OS Security Hub API
  version: "1.0"
paths:
  /audit/run:
    post:
      consumes:
      - application/json
      description: Execute security audit script on remote server
      parameters:
      - description: Audit execution request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handlers.AuditRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.AuditResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Run audit script on remote server
      tags:
      - audit
  /health:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.HealthResponse'
      summary: Show the status of server.
      tags:
      - health
swagger: "2.0"
